WIP: migrate typhoon to new-mock
rodekruis/IBF-system pull request #1488
Opened 2024-03-25 15:50 UTC by jannisvisser

2024-03-25 15:51 UTC, jannisvisser commented
@arsforza FYI: I did some quick initial work on migrating typhoon to new mock, but I'm going to quit it now. Just so you know, whenever you get to it.

2025-01-17 12:45 UTC, jannisvisser commented
I also added a remaining flash-floods mock data refactor to this, that I touched upon while working on documentation (writing a guide on mock data).

2025-01-21 12:17 UTC, gulfaraz requested changes
It works! It mostly looks okay. I've left inline comments.

2025-01-21 12:17 UTC, gulfaraz commented on tests/integration/helpers/API-service/enum/mock-scenario.enum.ts
> +  WarningAndTrigger = 'warning-and-trigger',
Instead of a separate scenario for `warning-and-trigger`, is it possible to use `removeEvents: false` and call the mock endpoint once with `scenario: trigger` and again with `scenario: warning`?

2025-01-21 14:13 UTC, jannisvisser commented on services/API-service/src/api/admin-area-dynamic-data/admin-area-dynamic-data.service.ts
> +      const ROOT_DIR = path.resolve('./geoserver-volume/raster-files/output');
this was directly based on recommendation in a code scanning alert [here](https://github.com/rodekruis/IBF-system/security/code-scanning/3), but good to know!

2025-01-22 09:28 UTC, jannisvisser commented on services/API-service/src/scripts/mock.controller.ts
> +    description: 'default: ...',
good point. it was supposed to be filled in, explaining the different options. But this would become a very long string with all these scenarios. So indeed removed, and also removed the description for all other disaster-types. It doesn't add much on top of the scenario name anyway.

2025-01-22 09:28 UTC, jannisvisser commented on services/API-service/src/scripts/mock-helper.service.ts
> +    if (scenarioName === FlashFloodsScenario.NoTrigger) {
done

2025-01-22 09:33 UTC, jannisvisser commented on services/API-service/src/scripts/mock.service.ts
> +    let exposureUnits = indicators
Very valid point, done. In general there's indeed a lot of renaming that could be done. Let's try to do small/easy stuff a bit on the go, but if we have time/money there's definitely some bigger refactoring to do around this as well.

2025-01-22 09:40 UTC, jannisvisser commented on tests/integration/helpers/API-service/enum/mock-scenario.enum.ts
> +  WarningAndTrigger = 'warning-and-trigger',
in other disaster-types we also have a lot of multi-event scenarios, even as the default/trigger scenario (in both floods/UGA and flash-floods/MWI). Changing the setup like you propose would also prevent to easily mock those trigger scenarios from the front-end.

So for now I propose to leave it, but we can re-evaluate at any moment.

2025-01-22 09:42 UTC, jannisvisser commented on services/API-service/src/scripts/mock.controller.ts
> +  @Roles(UserRole.Admin)
I think this is a good idea. I propose to include this in the 'remove heavy-rain' item, which allows to remove scripts.service and for mock-all to really be equal accross all disaster-types. Is that OK?

2025-01-22 10:28 UTC, jannisvisser commented
@gulfaraz I did a commit which includes
- PR comments processed
- I found that mock/all with triggered: false was not working. I fixed this (which needed a small hack, but made a note to solve that when refactoring /mock/all.

Given that these are minor things (and just about mock and tests pass) I will merge this already, so I can start the release.

2025-01-22 10:28 UTC, merged