Add E2E test for: [Trigger] Info icon is clickable and opens popover
rodekruis/IBF-system pull request #1878
Opened 2024-12-30 15:25 UTC by Piotrk39

## Describe your changes

Adds test for validating info icons by warnings in chat section.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added tests wherever relevant
- [ ] I have made sure that all automated checks pass before requesting a review

2025-01-02 11:10 UTC, jannisvisser commented on tests/e2e/tests/ChatSection/ChatInfoButtonOpenPopOver.spec.ts
> +// https://app.qase.io/project/IBF?case=45&previewMode=side&suite=6
the test case in Qase is not filled in. I think it makes sense to always start with that right before writing the test?

2025-01-02 11:10 UTC, jannisvisser commented on tests/e2e/Pages/ChatComponent.ts
> +    const countInfoButtons = await this.infoButtons.count();
so this tests all occurences of <app-tooltip> in the portal? so both the one in chat.component.html and in event-speech-bubble.component? (I guess not the one in river-gauge-popup-content as that is not opened at this stage).

Is it indeed the purpose of this test to test both the overall warning message tooltip, and the event-specific tooltip (see screenshot)

2025-01-02 11:12 UTC, jannisvisser requested changes
he piotr, test itself looks clear I think, but still have some questions.

2025-01-02 11:12 UTC, jannisvisser commented on tests/e2e/tests/ChatSection/ChatInfoButtonOpenPopOver.spec.ts
> +    await chat.chatColumnIsVisibleForTriggerState({
is this meant as a check to wait for the chat section to be fully loaded? if so, does it thereby fully cover another test case already maybe, which could therefore be deleted?

2025-01-06 07:43 UTC, Piotrk39 commented on tests/e2e/tests/ChatSection/ChatInfoButtonOpenPopOver.spec.ts
> +// https://app.qase.io/project/IBF?case=45&previewMode=side&suite=6
I forgot to paste, it should be there now.

2025-01-06 07:44 UTC, Piotrk39 commented on tests/e2e/Pages/ChatComponent.ts
> +    const countInfoButtons = await this.infoButtons.count();
It is supposed to test only the info buttons by the events.

2025-01-06 07:44 UTC, Piotrk39 commented on tests/e2e/tests/ChatSection/ChatInfoButtonOpenPopOver.spec.ts
> +    await chat.chatColumnIsVisibleForTriggerState({
I will actually come back to it when I do the refactor because many tests theoretically can be combined. I will do it soon in a separate PR. If this is alright with you?

2025-01-06 09:07 UTC, jannisvisser commented on tests/e2e/Pages/ChatComponent.ts
> +    const countInfoButtons = await this.infoButtons.count();
OK, cleared up that the top info-btn is only showing when the text is red, so not appearing in the test case.

Agreed to try to instead put the testId in app-tooltip of event-speech-bubble.component instead of tooltip.component itself.

2025-01-06 10:14 UTC, Piotrk39 commented on tests/e2e/Pages/ChatComponent.ts
> +    const countInfoButtons = await this.infoButtons.count();
It seems like the tooltips were separated between trigger event and event so I added it twice. Please verify that this is indeed correct implementation.

2025-01-06 16:00 UTC, jannisvisser commented on tests/e2e/Pages/ChatComponent.ts
> +    const countInfoButtons = await this.infoButtons.count();
I think that's fine. But I'm surprised the test succeeds, because this.infoButtons is now an array of <app-tooltips> and no longer an array of <ion-buttons>, so in line 209 below I would think that infoButton.click() shouldn't work any more. And instead you would need to locate the ion-button element. Can you confirm this is going allright? Also, the naming should be changed accordingly.

2025-01-06 16:53 UTC, Piotrk39 commented on tests/e2e/Pages/ChatComponent.ts
> +    const countInfoButtons = await this.infoButtons.count();
In practice it does not matter how the array is constructed as long as the testid is the same for both buttons they are treated equally. I can of course change it for event-tooltip and trigger-event-tooltip if it makes it clearer. I also changed the name of the function and it's variables.

2025-01-06 19:31 UTC, jannisvisser approved these changes

2025-01-06 19:31 UTC, merged