fix: show triggered disaster and fix left to right order of disaster …
rodekruis/IBF-system pull request #871
Opened 2021-09-13 07:30 UTC by SwatiTh

…AB#9317 AB#9318

2021-09-13 09:10 UTC, jannisvisser requested changes
@SwatiTh the 'show triggered disasterType by default' part works, however:
- I think there was miscommunication on the other requirement. Because the point was that floods should always be on the left, malaria on the right (of course not hard-coded like that, but based on the order they are entered in countries.json)

I also have some comments on the way this is coded
- You specifically use 'floods' in your code, but this is not robust. This code should also work in the future for a case where there are multiple disasterTypes of which floods is not one.
- I'm not sure that what extent using a timeout is best practice. There should always be a more robust solution, which actually knows that the required input is ready, instead of 'hoping' it's ready after 2000ms. @gulfaraz do you have input on this point?
- Please split your code in smaller functions (with clear names), instead of writing one long function. At least the whole new part you added should be split off in a separate function, but maybe even in multiple. This helps the readability.

2021-09-17 08:57 UTC, jannisvisser requested changes
@SwatiTh this works now, except that when both are non-triggered I see neither as the selected disaster.
![image](https://user-images.githubusercontent.com/18136553/133754330-74a4cc98-214b-4ac4-97df-3fdcaebf87f4.png)

2021-09-17 13:59 UTC, jannisvisser requested changes
@SwatiTh now it's wrong again in the following screenshot. Malaria is not selected while it is the only one triggered.

![image](https://user-images.githubusercontent.com/18136553/133794883-4a95fa29-28f1-4ce9-8f3f-f97249de0fd3.png)

2021-09-17 14:14 UTC, SwatiTh commented
Hi @jannisvisser ,  Please check again, I can see the selection.
<img width="735" alt="malaria-triggered " src="https://user-images.githubusercontent.com/86838833/133797363-edf29720-8ecc-4e5e-815d-e871e1262e2a.png">

2021-09-17 15:07 UTC, jannisvisser commented on interfaces/IBF-dashboard/src/app/components/disaster-type/disaster-type.component.ts
>        this.disasterTypes.forEach((disasterType) => {
@SwatiTh Maybe you should before this line order the disasterTypes (alphabetically) to make sure they're always in the same order.

2021-09-20 08:27 UTC, jannisvisser approved these changes
@SwatiTh looks good now!

Not sure if this latest commit also fixed the default selection issue (not sure how), but either way it works now. Go ahead and merge.

![image](https://user-images.githubusercontent.com/18136553/133974588-be804caa-4851-42fc-aa63-8ff24461740c.png)

2021-09-20 08:32 UTC, merged